config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :users, only:[:index, :show]
  resources :teslas, only:[:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :tesla
    belongs_to  :user
end

app/models/tesla.rb
class Tesla < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :teslas, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/teslas_controller.rb
class TeslasController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

    def index 
        # tesla = Tesla.all 
        # render json: tesla
    end

    def show 
        # tesla = Tesla.find(params[:id])
        # render json: tesla, status: :ok, serializer: TeslaUserSerializer
    end
    
    private
    def render_not_found
        render json: {error: "User Not Found"}, status: :not_found
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

    def index 
        users = User.all 
        render json: users
    end

    def show 
        user = User.find(params[:id])
        render json: user, status: :ok, serializer: UserTeslaSerializer  
    end

    private
    
    def render_not_found
        render json: {error: "User Not Found"}, status: :not_found
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/teslas_helper.rb
module TeslasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teslaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teslas/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container-fluid"  style="height:100vh ; background-image: rgb(198, 242, 255);    ">


    <% teslas = Tesla.all %>
        <% teslas.each do |tesla| %>
            <div class="tesla-details"
            style="background-image: url(<%= tesla.image_url %>); background-size: cover; background-position: center; background-repeat: no-repeat; height: 100vh; width: 100%;">
                <div class="tesla-content">
                    <h1 class="card-text" ><%= tesla.model %></h1>
                    <p>Order Online For Touchless Delivery</p>
                    </div>
                    <%= link_to "Custom Order", tesla_path(tesla), class: "btn btn-primary" %> 
                    

            </div>
        <% end %>

</div>
    

</body>
</html>

app/views/teslas/show.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container-fluid"  style="height:100vh ; background-image: rgb(198, 242, 255);">
  <% tesla = Tesla.find(params[:id]) %>
      <h1><%= tesla.model %></h1>
 <div class="row" style="margin-top: 100px;">
      <div class="col-6 ">
          <img src="<%= tesla.image_url %>"
          style="
          float: left;
          display: block;
          text-align: left;
          margin-left: auto;
          margin-right: 15px;
          width: 40vw;;
          height:40vh;"
          alt="<%= tesla.model %>">
      </div>
   <div class="col-6 ">
     <p class="card-text"><%= tesla.description %></p>
        <p class="card-text">$<%= tesla.price %></p>
         <p class="card-text">In Stock: <%= tesla.instock %> </p>

          <h2>Reviews</h2>
          <% users = tesla.users.uniq %>
          <% users.each do |user| %>

         <h5><%= user.name %></h5>
         <p><%= user.comment %></p>
         <% end %>
    </div>
  </div>
</div>
    
</body>
</html>


 